import flask
from flask import Flask, request, jsonify
import os
import pickle
import face_recognition
import numpy as np
from io import BytesIO
import time

# --- Global Constants ---
# These should be consistent with the files generated by your Tkinter admin app
ENCODINGS_FILE = 'voter_encodings.pkl'
MODEL_FILE = 'voter_face_recognition_model.pkl'

# --- Flask API Setup ---
# Global variables to store the loaded KNN model and raw encodings/IDs
current_knn_model = None
known_face_encodings_data = []
known_face_ids_data = []

# Global variables to track last load times
last_model_load_time = 0
last_encodings_load_time = 0

def load_model():
    """
    Loads the trained KNN model and raw face encodings/IDs from respective files,
    only if they are new or updated.
    """
    global current_knn_model, known_face_encodings_data, known_face_ids_data
    global last_model_load_time, last_encodings_load_time

    # --- Load KNN model ---
    if not os.path.exists(MODEL_FILE):
        if current_knn_model is not None:
            print(f"Warning: Model file not found at {MODEL_FILE}. Unloading current model.")
            current_knn_model = None
        last_model_load_time = 0
    else:
        current_model_mtime = os.path.getmtime(MODEL_FILE)
        if current_knn_model is None or current_model_mtime > last_model_load_time:
            try:
                with open(MODEL_FILE, 'rb') as f:
                    current_knn_model = pickle.load(f)
                last_model_load_time = current_model_mtime
                print(f"Successfully loaded/reloaded KNN model from {MODEL_FILE}")
            except Exception as e:
                print(f"Error loading model from {MODEL_FILE}: {e}")
                current_knn_model = None
                last_model_load_time = 0

    # --- Load raw encodings and IDs ---
    if not os.path.exists(ENCODINGS_FILE):
        if known_face_encodings_data or known_face_ids_data:
            print(f"Warning: Encodings file not found at {ENCODINGS_FILE}. Clearing current encodings.")
            known_face_encodings_data = []
            known_face_ids_data = []
        last_encodings_load_time = 0
    else:
        current_encodings_mtime = os.path.getmtime(ENCODINGS_FILE)
        if not known_face_encodings_data or current_encodings_mtime > last_encodings_load_time:
            try:
                with open(ENCODINGS_FILE, 'rb') as f:
                    data = pickle.load(f)
                    known_face_encodings_data = data.get('encodings', [])
                    known_face_ids_data = data.get('ids', [])
                last_encodings_load_time = current_encodings_mtime
                print(f"Successfully loaded/reloaded {len(known_face_encodings_data)} known face encodings from {ENCODINGS_FILE}")
            except Exception as e:
                print(f"Error loading encodings from {ENCODINGS_FILE}: {e}")
                known_face_encodings_data = []
                known_face_ids_data = []
                last_encodings_load_time = 0


app = Flask(__name__)

# Initial load when the Flask app starts
load_model()

@app.route('/recognize', methods=['POST'])
def recognize_face():
    # Always attempt to load the freshest model and encodings at the start of each request
    load_model()

    global current_knn_model, known_face_encodings_data, known_face_ids_data

    if 'image' not in request.files:
        return jsonify({'status': 'error', 'message': 'No image file provided'}), 400

    file = request.files['image']
    if file.filename == '':
        return jsonify({'status': 'error', 'message': 'No selected image file'}), 400

    try:
        # Read the image file content into a BytesIO object
        image_stream = BytesIO(file.read())
        # Load image using face_recognition (Pillow will handle it)
        image = face_recognition.load_image_file(image_stream)

        face_locations = face_recognition.face_locations(image)

        if len(face_locations) == 0:
            return jsonify({'status': 'success', 'voter_id': 'No face found'}), 200
        elif len(face_locations) > 1:
            return jsonify({'status': 'success', 'voter_id': 'Multiple faces found'}), 200
        else:
            face_encoding = face_recognition.face_encodings(image, face_locations)[0]

            # Ensure model and encodings are loaded after `load_model()` call
            if current_knn_model is None or not known_face_encodings_data:
                return jsonify({'status': 'error', 'message': 'Recognition model or encodings not loaded or found.'}), 500

            # Predict the voter ID using the KNN model
            # First, find the closest known face encoding
            distances = face_recognition.face_distance(known_face_encodings_data, face_encoding)
            min_distance_idx = np.argmin(distances)

            # A common threshold for face recognition (lower is more strict)
            # You might need to tune this threshold based on your dataset
            if distances[min_distance_idx] < 0.6:
                # If close enough, use the KNN classifier to get the predicted ID
                # Note: This assumes KNeighborsClassifier's .predict() can be used on a single encoding
                # and that the model is correctly trained with X_train_ and y_train_.
                # The current setup where KNN model is pickled and loaded works for this.
                predicted_id = current_knn_model.predict([face_encoding])[0]
                return jsonify({'status': 'success', 'voter_id': predicted_id}), 200
            else:
                return jsonify({'status': 'success', 'voter_id': 'Unknown'}), 200

    except Exception as e:
        return jsonify({'status': 'error', 'message': f'Error processing image: {e}'}), 500


if __name__ == '__main__':
    print("Flask app setup complete. To run, please execute `app.run(host='0.0.0.0', port=5000)` in a non-blocking manner or via a service like ngrok.")
    print("For example, after setting up ngrok, you can call `app.run(host='0.0.0.0', port=5000)` in a separate thread or use `!python -c 'from your_script import app; app.run(host=\"0.0.0.0\", port=5000)' &` for background execution in a terminal.")
